apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: k8s-native-tutorial-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: k8s-native-tutorial-app
  template:
    metadata:
      labels:
        app: k8s-native-tutorial-app
    spec:
      containers:
        - name: k8s-native-tutorial-app
          imagePullPolicy: Always
          image: docker.io/ashakirin/k8s-native-tutorial-app:0.0.1-SNAPSHOT
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
