management:
  endpoints:
    web:
      exposure:
        include: "*"

foo-url: http://localhost.org:8081

spring:
  cloud:
    gateway:
      httpclient:
        proxy:
          host: proxyhost
          port: 8888
      routes:
#        - id: foo
#          uri: ${foo-url}
#          predicates:
#            - Path=/foo/**
#          filters:
#            - StripPrefix=0
#            - RewritePath=/(?<segment>.*), /foo/hello
        - id: bar
          uri: http://localhost:8082
          predicates:
            - Path=/bar/**
          filters:
            - StripPrefix=0

httpbin-url: http://httpbin.org:80
