apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-rest
  template:
    metadata:
      labels:
        app: hello-rest
    spec:
      containers:
        - name: hello-rest
          imagePullPolicy: IfNotPresent
          image: docker.io/ashakirin/hello-rest