apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
  labels:
    run: {{.Chart.Name}}
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{.Chart.Name}}
  type: NodePort
