spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: local-test-user
    password: local-test-secret
    driver-class-name: com.mysql.cj.jdbc.Driver