spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 3
          max-interval: 10s
          multiplier: 1
