server:
  port: 9080

spring:
  application:
    name: basic-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

logbook:
  filter:
    enabled: true



logging:
  level:
    org:
      zalando:
        logbook: TRACE

kafka:
  bootstrap-servers: localhost:9092