spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    driverClassName: org.h2.Driver
    username: sa
    password: test
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE