server:
  port: 8092

resilience4j.circuitbreaker:
  instances:
    processService:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 1
      waitDurationInOpenState: 50s
      failureRateThreshold: 1
