server:
  port: 9081

basic:
  hello:
    url: http://localhost:9080


spring:
  application:
    name: composite-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50
